name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    env:
      ASSEMBLY_FILE_VERSION: "3.0.0.${{ github.run_number }}"
      NUGET_PACKAGE_VERSION: "3.0.0-alpha.${{ github.run_number }}"
      PACKAGE_FILE: "Bin/Publish/Cassia-3.0.0.${{ github.run_number }}.zip"
      NUGET_FILE: "Bin/Publish/Cassia.3.0.0-alpha.${{ github.run_number }}.nupkg"

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.0
    
    - name: Build
      run: msbuild Cassia.targets

    - name: Publish package
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Source
        path: "${{ env.PACKAGE_FILE }}"
    - name: Publish NuGet
      uses: actions/upload-artifact@v1.0.0
      with:
        name: NuGet Package
        path: "${{ env.NUGET_FILE }}"
    
    - name: Push to NuGet Gallery
      run: dotnet nuget push -k ${{ secrets.NuGetAPIKey }} ${{ env.NUGET_FILE }}